object NotificationCommand "notify-host-by-incidentio" {
  command = [ "/etc/icinga2/scripts/incidentio_host_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    HOSTSTATE        = "$host.state$"
    HOSTOUTPUT       = "$host.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}

object NotificationCommand "notify-service-by-incidentio" {
  command = [ "/etc/icinga2/scripts/incidentio_service_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    SERVICENAME      = "$service.name$"
    SERVICESTATE     = "$service.state$"
    SERVICEOUTPUT    = "$service.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}

object NotificationCommand "notify-host-by-discord" {
  command = [ "/etc/icinga2/scripts/discord_host_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    HOSTSTATE        = "$host.state$"
    HOSTOUTPUT       = "$host.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}

object NotificationCommand "notify-service-by-discord" {
  command = [ "/etc/icinga2/scripts/discord_service_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    SERVICENAME      = "$service.name$"
    SERVICESTATE     = "$service.state$"
    SERVICEOUTPUT    = "$service.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}

object NotificationCommand "notify-host-by-slack" {
  command = [ "/etc/icinga2/scripts/slack_host_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    HOSTSTATE        = "$host.state$"
    HOSTOUTPUT       = "$host.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}

object NotificationCommand "notify-service-by-slack" {
  command = [ "/etc/icinga2/scripts/slack_service_notification.sh" ]
  env = {
    NOTIFICATIONTYPE = "$notification.type$"
    HOSTNAME         = "$host.name$"
    SERVICENAME      = "$service.name$"
    SERVICESTATE     = "$service.state$"
    SERVICEOUTPUT    = "$service.output$"
    LONGDATETIME     = "$icinga.long_date_time$"
  }
}
